import { Transfer } from '@/types/transfer';

export interface TransferEntry {
  player: string;
  transferType: 'Transfer In' | 'Transfer Out' | 'Loan In' | 'Loan Out' | 'Released' | 'End of loan';
  club: string;
}

export const TEAMS_TRANSFER_DATA: Record<string, TransferEntry[]> = {
  'Arsenal': [
    // TRANSFERS OUT - RELEASED
    { player: 'Jorginho', transferType: 'Released', club: 'Flamengo' },
    { player: 'Nathan Butler-Oyedeji', transferType: 'Released', club: 'Lausanne' },
    { player: 'Elian Quesada-Thorn', transferType: 'Released', club: 'Alajuelense' },
    { player: 'Kieran Tierney', transferType: 'Released', club: 'Celtic' },
    { player: 'Takehiro Tomiyasu', transferType: 'Released', club: '-' },
    // TRANSFERS OUT - END OF LOAN
    { player: 'Raheem Sterling', transferType: 'End of loan', club: 'Chelsea' },
    { player: 'Neto', transferType: 'End of loan', club: 'Bournemouth' },
    // TRANSFERS OUT
    { player: 'Nuno Tavares', transferType: 'Transfer Out', club: 'Lazio' },
    { player: 'Marquinhos', transferType: 'Transfer Out', club: 'Cruzeiro' },
    { player: 'Sambi Lokonga', transferType: 'Transfer Out', club: 'Hamburger SV' },
    // TRANSFERS IN
    { player: 'Kepa Arrizabalaga', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Martin Zubimendi', transferType: 'Transfer In', club: 'Real Sociedad' },
    { player: 'Christian Norgaard', transferType: 'Transfer In', club: 'Brentford' },
    { player: 'Noni Madueke', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Cristhian Mosquera', transferType: 'Transfer In', club: 'Valencia' },
    { player: 'Viktor Gyokeres', transferType: 'Transfer In', club: 'Sporting' },
    { player: 'Eberechi Eze', transferType: 'Transfer In', club: 'Crystal Palace' },
    // LOANS OUT
    { player: 'Karl Hein', transferType: 'Loan Out', club: 'Werder Bremen' },
    { player: 'Ismeal Kabia', transferType: 'Loan Out', club: 'Shrewsbury Town' },
    { player: 'Lucas Martin Nygaard', transferType: 'Loan Out', club: 'Brabrand IF' },
    { player: 'Fabio Vieira', transferType: 'Loan Out', club: 'Hamburger SV' },
    { player: 'Jakub Kiwior', transferType: 'Loan Out', club: 'Porto' },
    { player: 'Oleksandr Zinchenko', transferType: 'Loan Out', club: 'Nottingham Forest' },
    { player: 'Reiss Nelson', transferType: 'Loan Out', club: 'Brentford' },
    { player: 'Maldini Kacurri', transferType: 'Loan Out', club: 'Morecambe' },
    // LOANS IN
    { player: 'Piero Hincapie', transferType: 'Loan In', club: 'Bayer Leverkusen' }
  ],
  'Aston Villa': [
    { player: 'Yasin Ozcan', transferType: 'Transfer In', club: 'Kasimpasa' },
    { player: 'Robin Olsen', transferType: 'Released', club: 'Malmo' },
    { player: 'Josh Feeney', transferType: 'Loan Out', club: 'Huddersfield' },
    { player: 'Rico Richards', transferType: 'Transfer Out', club: 'Port Vale' },
    { player: 'Kortney Hause', transferType: 'Released', club: '-' },
    { player: 'Marcus Rashford', transferType: 'End of loan', club: 'Man Utd' },
    { player: 'Marco Asensio', transferType: 'End of loan', club: 'PSG' },
    { player: 'Axel Disasi', transferType: 'End of loan', club: 'Chelsea' },
    { player: 'Hesler Hayden', transferType: 'Transfer Out', club: 'Coventry' },
    { player: 'Zepiqueno Redmond', transferType: 'Transfer In', club: 'Feyenoord' },
    { player: 'Philippe Coutinho', transferType: 'Transfer Out', club: 'Vasco da Gama' },
    { player: 'Kosta Nedelkovic', transferType: 'Loan Out', club: 'RB Leipzig' },
    { player: 'Oliwier Zych', transferType: 'Loan Out', club: 'Rakow Czestochowa' },
    { player: 'Finley Munroe', transferType: 'Loan Out', club: 'Swindon' },
    { player: 'Tommi O\'Reilly', transferType: 'Loan Out', club: 'Crewe' },
    { player: 'Sil Swinkels', transferType: 'Loan Out', club: 'Exeter City' },
    { player: 'Marco Bizot', transferType: 'Transfer In', club: 'Brest' },
    { player: 'Enzo Barrenechea', transferType: 'Loan Out', club: 'Benfica' },
    { player: 'Modou Keba Cisse', transferType: 'Transfer In', club: 'LASK' },
    { player: 'Kyrie Pierre', transferType: 'Transfer Out', club: 'Brentford' },
    { player: 'Louie Barry', transferType: 'Loan Out', club: 'Sheffield United' },
    { player: 'Filip Marschall', transferType: 'Transfer Out', club: 'Stevenage' },
    { player: 'Ethan Amundsen-Day', transferType: 'Transfer Out', club: 'Hamarkameratene' },
    { player: 'Yasin Ozcan', transferType: 'Loan Out', club: 'Anderlecht' },
    { player: 'Evann Guessand', transferType: 'Transfer In', club: 'Nice' },
    { player: 'Joe Gauci', transferType: 'Loan Out', club: 'Port Vale' },
    { player: 'Kerr Smith', transferType: 'Loan Out', club: 'Barrow' },
    { player: 'Jacob Ramsey', transferType: 'Transfer Out', club: 'Newcastle' },
    { player: 'Leander Dendoncker', transferType: 'Transfer Out', club: 'Real Oviedo' },
    { player: 'Leon Bailey', transferType: 'Loan Out', club: 'AS Roma' },
    { player: 'Lewis Dobbin', transferType: 'Loan Out', club: 'Preston North End' },
    { player: 'Alex Moreno', transferType: 'Transfer Out', club: 'Girona' },
    { player: 'Victor Lindelof', transferType: 'Transfer In', club: '-' },
    { player: 'Samuel Iling Jr', transferType: 'Loan Out', club: 'West Bromwich Albion' },
    { player: 'Zepiqueno Redmond', transferType: 'Loan Out', club: 'Huddersfield Town' },
    { player: 'Jadon Sancho', transferType: 'Loan In', club: 'Manchester United' },
    { player: 'Harvey Elliott', transferType: 'Loan In', club: 'Liverpool' },
    { player: 'Tristan Rowe', transferType: 'Loan Out', club: 'Annecy' }
  ],
  'Bournemouth': [
    { player: 'Eli Junior Kroupi', transferType: 'Transfer In', club: 'Lorient' },
    { player: 'Dean Huijsen', transferType: 'Transfer Out', club: 'Real Madrid' },
    { player: 'Jaidon Anthony', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Kepa Arrizabalaga', transferType: 'End of loan', club: 'Chelsea' },
    { player: 'Adrien Truffert', transferType: 'Transfer In', club: 'Rennes' },
    { player: 'Daniel Jebbison', transferType: 'Loan Out', club: 'Preston' },
    { player: 'Max Aarons', transferType: 'Loan Out', club: 'Rangers' },
    { player: 'Milos Kerkez', transferType: 'Transfer Out', club: 'Liverpool' },
    { player: 'Joe Rothwell', transferType: 'Transfer Out', club: 'Rangers' },
    { player: 'Mark Travers', transferType: 'Transfer Out', club: 'Everton' },
    { player: 'Djordje Petrovic', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Neto', transferType: 'Transfer Out', club: 'Botafogo' },
    { player: 'Illia Zabarnyi', transferType: 'Transfer Out', club: 'Paris Saint-Germain' },
    { player: 'Bafode Diakite', transferType: 'Transfer In', club: 'Lille' },
    { player: 'Dango Ouattara', transferType: 'Transfer Out', club: 'Brentford' },
    { player: 'Ben Gannon-Doak', transferType: 'Transfer In', club: 'Liverpool' },
    { player: 'Amine Adli', transferType: 'Transfer In', club: 'Bayer Leverkusen' },
    { player: 'Luis Sinisterra', transferType: 'Loan Out', club: 'Cruzeiro' },
    { player: 'Philip Billing', transferType: 'Transfer Out', club: 'Midtjylland' },
    { player: 'Alex Paulsen', transferType: 'Loan Out', club: 'Lechia Gdansk' },
    { player: 'Ben Winterburn', transferType: 'Loan Out', club: 'Barnet' },
    { player: 'Veljko Milosavljevic', transferType: 'Transfer In', club: 'Red Star Belgrade' },
    { player: 'Zain Silcott-Duberry', transferType: 'Transfer Out', club: 'Olympiakos' },
    { player: 'Romain Faivre', transferType: 'Loan Out', club: 'Al Taawoun' },
    { player: 'Dominic Sadi', transferType: 'Loan Out', club: 'FK Novi Pazar' },
    { player: 'Daniel Adu-Adjei', transferType: 'Transfer Out', club: 'HNK Rijeka' }
  ],
  'Leeds United': [
    { player: 'Josuha Guilavogui', transferType: 'Released', club: '-' },
    { player: 'Joe Rothwell', transferType: 'End of loan', club: 'Bournemouth' },
    { player: 'Manor Solomon', transferType: 'End of loan', club: 'Spurs' },
    { player: 'Lukas Nmecha', transferType: 'Transfer In', club: 'Wolfsburg' },
    { player: 'Sebastiaan Bornauw', transferType: 'Transfer In', club: 'Wolfsburg' },
    { player: 'Joe Snowdon', transferType: 'Released', club: 'Swindon' },
    { player: 'Jaka Bijol', transferType: 'Transfer In', club: 'Udinese' },
    { player: 'Junior Firpo', transferType: 'Released', club: 'Real Betis' },
    { player: 'Max Wober', transferType: 'Loan Out', club: 'Werder Bremen' },
    { player: 'Max McFadden', transferType: 'Released', club: 'Spurs' },
    { player: 'Gabriel Gudmundsson', transferType: 'Transfer In', club: 'Lille' },
    { player: 'Louis Enahoro-Marcus', transferType: 'Transfer In', club: 'Liverpool' },
    { player: 'Sean Longstaff', transferType: 'Transfer In', club: 'Newcastle' },
    { player: 'Anton Stach', transferType: 'Transfer In', club: 'TSG Hoffenheim' },
    { player: 'Lucas Perri', transferType: 'Transfer In', club: 'Lyon' },
    { player: 'Mateo Joseph', transferType: 'Loan Out', club: 'RCD Mallorca' },
    { player: 'Joe Gelhardt', transferType: 'Loan Out', club: 'Hull City' },
    { player: 'Dominic Calvert-Lewin', transferType: 'Transfer In', club: 'Everton' },
    { player: 'Noah Okafor', transferType: 'Transfer In', club: 'AC Milan' },
    { player: 'James Justin', transferType: 'Transfer In', club: 'Leicester' },
    { player: 'Sam Greenwood', transferType: 'Transfer Out', club: 'Pogon Szczecin' },
    { player: 'Patrick Bamford', transferType: 'Released', club: '-' },
    { player: 'Isaac Schmidt', transferType: 'Loan Out', club: 'Werder Bremen' },
    { player: 'Largie Ramazani', transferType: 'Loan Out', club: 'Valencia' },
    { player: 'Darko Gyabi', transferType: 'Transfer Out', club: 'Hull City' }
  ],
  'Brentford': [
    { player: 'Ben Mee', transferType: 'Released', club: '-' },
    { player: 'Michael Kayode', transferType: 'Transfer In', club: 'Fiorentina' },
    { player: 'Ben Winterbottom', transferType: 'Released', club: 'Barrow' },
    { player: 'Romelle Donovan', transferType: 'Transfer In', club: 'Birmingham City' },
    { player: 'Caoimhin Kelleher', transferType: 'Transfer In', club: 'Liverpool' },
    { player: 'Mark Flekken', transferType: 'Transfer Out', club: 'Bayer Leverkusen' },
    { player: 'Tony Yogane', transferType: 'Loan Out', club: 'Dundee' },
    { player: 'Antoni Milambo', transferType: 'Transfer In', club: 'Feyenoord' },
    { player: 'Christian Norgaard', transferType: 'Transfer Out', club: 'Arsenal' },
    { player: 'Jordan Henderson', transferType: 'Transfer In', club: 'Ajax' },
    { player: 'Ben Krauhaus', transferType: 'Loan Out', club: 'Bromley' },
    { player: 'Kyrie Pierre', transferType: 'Transfer In', club: 'Aston Villa' },
    { player: 'Bryan Mbeumo', transferType: 'Transfer Out', club: 'Man Utd' },
    { player: 'Emeka Peters', transferType: 'Transfer Out', club: 'Feyenoord' },
    { player: 'Ji-soo Kim', transferType: 'Loan Out', club: 'Kaiserslautern' },
    { player: 'Benjamin Fredrick', transferType: 'Loan Out', club: 'Dender' },
    { player: 'Ryan Trevitt', transferType: 'Loan Out', club: 'Wigan Athletic' },
    { player: 'Dango Ouattara', transferType: 'Transfer In', club: 'AFC Bournemouth' },
    { player: 'Jayden Meghoma', transferType: 'Loan Out', club: 'Rangers' },
    { player: 'Mads Roerslev', transferType: 'Transfer Out', club: 'Southampton' },
    { player: 'Yoane Wissa', transferType: 'Transfer Out', club: 'Newcastle' },
    { player: 'Reiss Nelson', transferType: 'Loan In', club: 'Arsenal' }
  ],
  'Brighton & Hove Albion': [
    { player: 'Tommy Watson', transferType: 'Transfer In', club: 'Sunderland' },
    { player: 'Yun Do-young', transferType: 'Transfer In', club: 'Daejon Hana Citizen' },
    { player: 'Charalampos Kostoulas', transferType: 'Transfer In', club: 'Olympiacos' },
    { player: 'Diego Coppola', transferType: 'Transfer In', club: 'Verona' },
    { player: 'Nils Ramming', transferType: 'Transfer In', club: 'Eintracht Frankfurt' },
    { player: 'James Beadle', transferType: 'Loan Out', club: 'Birmingham City' },
    { player: 'Joao Pedro', transferType: 'Transfer Out', club: 'Chelsea' },
    { player: 'Valentin Barco', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Olivier Boscagli', transferType: 'Transfer In', club: 'PSV' },
    { player: 'Odel Offiah', transferType: 'Transfer Out', club: 'Preston' },
    { player: 'Amario Cozier-Duberry', transferType: 'Loan Out', club: 'Bolton' },
    { player: 'Maxim De Cuyper', transferType: 'Transfer In', club: 'Club Brugge' },
    { player: 'Mark O\'Mahony', transferType: 'Loan Out', club: 'Reading' },
    { player: 'Simon Adingra', transferType: 'Transfer Out', club: 'Sunderland' },
    { player: 'Jamie Mullins', transferType: 'Transfer Out', club: 'Wycombe' },
    { player: 'Yoon Do-young', transferType: 'Loan Out', club: 'Excelsior' },
    { player: 'Caylan Vickers', transferType: 'Loan Out', club: 'Barnsley' },
    { player: 'Evan Ferguson', transferType: 'Loan Out', club: 'Roma' },
    { player: 'Pervis Estupinan', transferType: 'Transfer Out', club: 'AC Milan' },
    { player: 'Carl Rushworth', transferType: 'Loan Out', club: 'Coventry' },
    { player: 'Eiran Cashin', transferType: 'Loan Out', club: 'Birmingham City' },
    { player: 'Sean Keogh', transferType: 'Transfer In', club: 'Dundalk' },
    { player: 'Kofi Shaw', transferType: 'Transfer In', club: 'Bristol Rovers' },
    { player: 'Kamari Doyle', transferType: 'Loan Out', club: 'Reading' },
    { player: 'Malick Yalcouye', transferType: 'Loan Out', club: 'Swansea City' },
    { player: 'Andrew Moran', transferType: 'Loan Out', club: 'Los Angeles FC' },
    { player: 'Abdallah Sima', transferType: 'Transfer Out', club: 'Lens' },
    { player: 'Adrian Mazilu', transferType: 'Transfer Out', club: 'Dinamo Bucharest' },
    { player: 'Tariq Lamptey', transferType: 'Transfer Out', club: 'Fiorentina' },
    { player: 'Julio Enciso', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Facundo Buonanotte', transferType: 'Loan Out', club: 'Chelsea' },
    { player: 'Jeremy Sarmiento', transferType: 'Loan Out', club: 'Cremonese' },
    { player: 'Igor Julio', transferType: 'Loan Out', club: 'West Ham' },
    { player: 'Matt O\'Riley', transferType: 'Loan Out', club: 'Marseille' }
  ],
  'Burnley': [
    { player: 'Bashir Humphreys', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Jaidon Anthony', transferType: 'Transfer In', club: 'Bournemouth' },
    { player: 'Marcus Edwards', transferType: 'Transfer In', club: 'Sporting' },
    { player: 'Zian Flemming', transferType: 'Transfer In', club: 'Millwall' },
    { player: 'Nathan Redmond', transferType: 'Released', club: '-' },
    { player: 'Jonjo Shelvey', transferType: 'Released', club: '-' },
    { player: 'Jeremy Sarmiento', transferType: 'End of loan', club: 'Brighton' },
    { player: 'CJ Egan-Riley', transferType: 'Released', club: 'Marseille' },
    { player: 'Max Weiss', transferType: 'Transfer In', club: 'Karlsruher' },
    { player: 'Quilindschy Hartman', transferType: 'Transfer In', club: 'Feyenoord' },
    { player: 'Axel Tuanzebe', transferType: 'Transfer In', club: 'Ipswich' },
    { player: 'Loum Tchaouna', transferType: 'Transfer In', club: 'Lazio' },
    { player: 'Kyle Walker', transferType: 'Transfer In', club: 'Man City' },
    { player: 'Jacob Bruun Larsen', transferType: 'Transfer In', club: 'Stuttgart' },
    { player: 'Andreas Hountondji', transferType: 'Loan Out', club: 'St Pauli' },
    { player: 'Sam Waller', transferType: 'Loan Out', club: 'Crewe' },
    { player: 'Han-Noah Massengo', transferType: 'Transfer Out', club: 'Augsburg' },
    { player: 'James Trafford', transferType: 'Transfer Out', club: 'Man City' },
    { player: 'Owen Dodgson', transferType: 'Loan Out', club: 'Stockport County' },
    { player: 'Joe Bauress', transferType: 'Loan Out', club: 'Accrington Stanley' },
    { player: 'Lesley Ugochukwu', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Martin Dubravka', transferType: 'Transfer In', club: 'Newcastle' },
    { player: 'Armando Broja', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Oluwaseun Adewumi', transferType: 'Loan Out', club: 'Cercle Brugge' },
    { player: 'Shurandy Sambo', transferType: 'Loan Out', club: 'Sparta Rotterdam' },
    { player: 'Luca Koleosho', transferType: 'Loan Out', club: 'Espanyol' },
    { player: 'Michael Obafemi', transferType: 'Loan Out', club: 'VfL Bochum' },
    { player: 'Darko Churlinov', transferType: 'Transfer Out', club: 'Kocaelispor' },
    { player: 'Florentino Luis', transferType: 'Loan In', club: 'Benfica' },
    { player: 'Aaron Ramsey', transferType: 'Loan Out', club: 'Leicester City' },
    { player: 'Manuel Benson', transferType: 'Loan Out', club: 'Swansea' }
  ],
  'Chelsea': [
    { player: 'Dario Essugo', transferType: 'Transfer In', club: 'Sporting' },
    { player: 'Bashir Humphreys', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Liam Delap', transferType: 'Transfer In', club: 'Ipswich' },
    { player: 'Mamadou Sarr', transferType: 'Transfer In', club: 'Strasbourg' },
    { player: 'Marcus Bettinelli', transferType: 'Transfer Out', club: 'Man City' },
    { player: 'Kepa Arrizabalaga', transferType: 'Transfer Out', club: 'Arsenal' },
    { player: 'Joao Pedro', transferType: 'Transfer In', club: 'Brighton' },
    { player: 'Jamie Gittens', transferType: 'Transfer In', club: 'Borussia Dortmund' },
    { player: 'Mathis Amougou', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Djordje Petrovic', transferType: 'Transfer Out', club: 'Bournemouth' },
    { player: 'Noni Madueke', transferType: 'Transfer Out', club: 'Arsenal' },
    { player: 'Caleb Wiley', transferType: 'Loan Out', club: 'Watford' },
    { player: 'Mike Penders', transferType: 'Loan Out', club: 'Strasbourg' },
    { player: 'Joao Felix', transferType: 'Transfer Out', club: 'Al-Nassr' },
    { player: 'Ishe Samuels-Smith', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Kendry Paez', transferType: 'Loan Out', club: 'Strasbourg' },
    { player: 'Jesse Derry', transferType: 'Transfer In', club: 'Crystal Palace' },
    { player: 'Mamadou Sarr', transferType: 'Loan Out', club: 'Strasbourg' },
    { player: 'Leo Castledine', transferType: 'Loan Out', club: 'Huddersfield' },
    { player: 'Jorrel Hato', transferType: 'Transfer In', club: 'Ajax' },
    { player: 'Estevao', transferType: 'Transfer In', club: 'Palmeiras' },
    { player: 'Kiernan Dewsbury-Hall', transferType: 'Transfer Out', club: 'Everton' },
    { player: 'Marc Guiu', transferType: 'Loan Out', club: 'Sunderland' },
    { player: 'Lesley Ugochukwu', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Armando Broja', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Renato Veiga', transferType: 'Transfer Out', club: 'Villarreal' },
    { player: 'Carney Chukwuemeka', transferType: 'Transfer Out', club: 'Borussia Dortmund' },
    { player: 'Aaron Anselmino', transferType: 'Loan Out', club: 'Borussia Dortmund' },
    { player: 'Christopher Nkunku', transferType: 'Transfer Out', club: 'AC Milan' },
    { player: 'Alejandro Garnacho', transferType: 'Transfer In', club: 'Manchester United' },
    { player: 'Alex Matos', transferType: 'Transfer Out', club: 'Sheffield United' },
    { player: 'Facundo Buonanotte', transferType: 'Loan In', club: 'Brighton' },
    { player: 'Jimmy-Jay Morgan', transferType: 'Loan Out', club: 'Peterborough United' },
    { player: 'Marc Guiu', transferType: 'Loan In', club: 'Sunderland' },
    { player: 'Nicolas Jackson', transferType: 'Loan Out', club: 'Bayern Munich' },
    { player: 'Ben Chilwell', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Ishe Samuels-Smith', transferType: 'Loan Out', club: 'Swansea City' },
    { player: 'Ronnie Stutter', transferType: 'Loan Out', club: 'Barnet' },
    { player: 'Emanuel Emegha', transferType: 'Transfer In', club: 'RC Strasbourg' },
    { player: 'David Datro Fofana', transferType: 'Loan Out', club: 'Fatih Karagumruk S.K.' }
  ],
  'Crystal Palace': [
    { player: 'Joel Ward', transferType: 'Released', club: '-' },
    { player: 'Jeffrey Schlupp', transferType: 'Released', club: 'Celtic' },
    { player: 'Louie Moulden', transferType: 'Released', club: 'Norwich' },
    { player: 'Walter Benitez', transferType: 'Transfer In', club: 'PSV Eindhoven' },
    { player: 'Owen Goodman', transferType: 'Loan Out', club: 'Huddersfield' },
    { player: 'Borna Sosa', transferType: 'Transfer In', club: 'Ajax' },
    { player: 'Danny Imray', transferType: 'Loan Out', club: 'Blackpool' },
    { player: 'Ademola Ola-Adebomi', transferType: 'Transfer Out', club: 'WSG Tirol' },
    { player: 'Tayo Adaramola', transferType: 'Loan Out', club: 'Leyton Orient' },
    { player: 'David Ozoh', transferType: 'Loan Out', club: 'Derby County' },
    { player: 'Rob Holding', transferType: 'Released', club: 'Colorado' },
    { player: 'Jesse Derry', transferType: 'Transfer Out', club: 'Chelsea' },
    { player: 'Malcolm Ebiowei', transferType: 'Transfer Out', club: 'Blackpool' },
    { player: 'Eberechi Eze', transferType: 'Transfer Out', club: 'Arsenal' },
    { player: 'Hindolo Mustapha', transferType: 'Loan Out', club: 'Nurnberg' },
    { player: 'Yeremy Pino', transferType: 'Transfer In', club: 'Villarreal' },
    { player: 'Odsonne Edouard', transferType: 'Transfer Out', club: 'RC Lens' },
    { player: 'Jaydee Canvot', transferType: 'Transfer In', club: 'Toulouse' },
    { player: 'Christantus Uche', transferType: 'Loan In', club: 'Getafe' },
    { player: 'Franco Umeh', transferType: 'Transfer Out', club: 'Portsmouth' }
  ],
  'Everton': [
    { player: 'Ashley Young', transferType: 'Released', club: '-' },
    { player: 'Asmir Begovic', transferType: 'Released', club: 'Leicester' },
    { player: 'Joao Virginia', transferType: 'Released', club: 'Sporting' },
    { player: 'Abdoulaye Doucoure', transferType: 'Released', club: 'Neom' },
    { player: 'Jack Harrison', transferType: 'End of loan', club: 'Leeds' },
    { player: 'Jesper Lindstrom', transferType: 'End of loan', club: 'Napoli' },
    { player: 'Orel Mangala', transferType: 'End of loan', club: 'Lyon' },
    { player: 'Armando Broja', transferType: 'End of loan', club: 'Chelsea' },
    { player: 'Charly Alcaraz', transferType: 'Transfer In', club: 'Flamengo' },
    { player: 'Mason Holgate', transferType: 'Released', club: 'Al-Gharafa' },
    { player: 'Neal Maupay', transferType: 'Released', club: '-' },
    { player: 'Thierno Barry', transferType: 'Transfer In', club: 'Villarreal' },
    { player: 'Mark Travers', transferType: 'Transfer In', club: 'Bournemouth' },
    { player: 'Jenson Metcalfe', transferType: 'Transfer Out', club: 'Bradford City' },
    { player: 'Adam Aznou', transferType: 'Transfer In', club: 'Bayern Munich' },
    { player: 'Kiernan Dewsbury-Hall', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Jack Grealish', transferType: 'Loan In', club: 'Man City' },
    { player: 'Reuben Gokah', transferType: 'Transfer In', club: 'Charlton Athletic' },
    { player: 'Dominic Calvert-Lewin', transferType: 'Released', club: 'Leeds United' },
    { player: 'Tom King', transferType: 'Transfer In', club: 'Wolves' },
    { player: 'Martin Sherif', transferType: 'Loan Out', club: 'Rotherham United' },
    { player: 'Francis Okoronkwo', transferType: 'Loan Out', club: 'Lincoln City' },
    { player: 'Tyler Dibling', transferType: 'Transfer In', club: 'Southampton' },
    { player: 'Isaac Heath', transferType: 'Loan Out', club: 'Accrington' },
    { player: 'Tyler Onyango', transferType: 'Loan Out', club: 'Stockport County' },
    { player: 'Youssef Chermiti', transferType: 'Transfer Out', club: 'Rangers' },
    { player: 'Harrison Armstrong', transferType: 'Loan Out', club: 'Preston North End' },
    { player: 'Merlin Rohl', transferType: 'Loan In', club: 'SC Freiburg' }
  ],
  'Fulham': [
    { player: 'Carlos Vinicius', transferType: 'Released', club: 'Gremio' },
    { player: 'Willian', transferType: 'Released', club: '-' },
    { player: 'Luca Ashby-Hammond', transferType: 'Released', club: 'Plymouth' },
    { player: 'Callum Osmand', transferType: 'Released', club: 'Celtic' },
    { player: 'Matt Dibley-Dias', transferType: 'Loan Out', club: 'Chesterfield' },
    { player: 'Luke Harris', transferType: 'Loan Out', club: 'Oxford' },
    { player: 'Steven Benda', transferType: 'Loan Out', club: 'Millwall' },
    { player: 'Benjamin Lecomte', transferType: 'Transfer In', club: 'Montpellier' },
    { player: 'Luc De Fougerolles', transferType: 'Loan Out', club: 'F.C.V. Dender' },
    { player: 'Olly Sanderson', transferType: 'Loan Out', club: 'Woking' },
    { player: 'Harvey Araujo', transferType: 'Loan Out', club: 'Colchester' },
    { player: 'Martial Godo', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Samuel Chukwueze', transferType: 'Loan In', club: 'AC Milan' },
    { player: 'Kevin', transferType: 'Transfer In', club: 'Shakhtar Donetsk' },
    { player: 'Lewis Kondau-Wall', transferType: 'Transfer In', club: '-' }
  ],
  'Liverpool': [
    { player: 'Giorgi Mamardashvili', transferType: 'Transfer In', club: 'Valencia' },
    { player: 'Trent Alexander-Arnold', transferType: 'Transfer Out', club: 'Real Madrid' },
    { player: 'Jeremie Frimpong', transferType: 'Transfer In', club: 'Bayer Leverkusen' },
    { player: 'Caoimhin Kelleher', transferType: 'Transfer Out', club: 'Brentford' },
    { player: 'Dominic Corness', transferType: 'Released', club: 'The New Saints' },
    { player: 'Jakub Ojrzynski', transferType: 'Released', club: 'Orebro' },
    { player: 'Armin Pecsi', transferType: 'Transfer In', club: 'Puskas Akademia' },
    { player: 'Vitezslav Jaros', transferType: 'Loan Out', club: 'Ajax' },
    { player: 'Florian Wirtz', transferType: 'Transfer In', club: 'Bayer Leverkusen' },
    { player: 'Nathaniel Phillips', transferType: 'Transfer Out', club: 'West Brom' },
    { player: 'Harvey Davies', transferType: 'Loan Out', club: 'Crawley' },
    { player: 'Milos Kerkez', transferType: 'Transfer In', club: 'Bournemouth' },
    { player: 'Freddie Woodman', transferType: 'Transfer In', club: 'Preston North' },
    { player: 'Jarell Quansah', transferType: 'Transfer Out', club: 'Bayer Leverkusen' },
    { player: 'Louis Enahoro-Marcus', transferType: 'Transfer Out', club: 'Leeds United' },
    { player: 'Hugo Ekitike', transferType: 'Transfer In', club: 'Eintracht Frankfurt' },
    { player: 'Owen Beck', transferType: 'Loan Out', club: 'Derby' },
    { player: 'Luis Diaz', transferType: 'Transfer Out', club: 'Bayern Munich' },
    { player: 'Tyler Morton', transferType: 'Transfer Out', club: 'Olympique Lyonnais' },
    { player: 'Isaac Mabaya', transferType: 'Loan Out', club: 'Wigan Athletic' },
    { player: 'Will Wright', transferType: 'Transfer In', club: 'Salford' },
    { player: 'Darwin Nunez', transferType: 'Transfer Out', club: 'Al-Hilal' },
    { player: 'Luca Stephenson', transferType: 'Loan Out', club: 'Dundee United' },
    { player: 'Giovanni Leoni', transferType: 'Transfer In', club: 'Parma' },
    { player: 'Ben Gannon-Doak', transferType: 'Transfer Out', club: 'AFC Bournemouth' },
    { player: 'Lewis Koumas', transferType: 'Loan Out', club: 'Birmingham City' },
    { player: 'James Balagizi', transferType: 'Loan Out', club: 'Forest Green Rovers' },
    { player: 'Kostas Tsimikas', transferType: 'Loan Out', club: 'Roma' },
    { player: 'Alexander Isak', transferType: 'Transfer In', club: 'Newcastle United' },
    { player: 'Harvey Elliott', transferType: 'Loan Out', club: 'Aston Villa' },
    { player: 'James McConnell', transferType: 'Loan Out', club: 'Ajax' }
  ],
  'Manchester City': [
    { player: 'Kevin De Bruyne', transferType: 'Transfer Out', club: 'Napoli' },
    { player: 'Jacob Wright', transferType: 'Transfer Out', club: 'Norwich City' },
    { player: 'Scott Carson', transferType: 'Released', club: '-' },
    { player: 'Rayan Ait-Nouri', transferType: 'Transfer In', club: 'Wolves' },
    { player: 'Marcus Bettinelli', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Rayan Cherki', transferType: 'Transfer In', club: 'Lyon' },
    { player: 'Tijjani Reijnders', transferType: 'Transfer In', club: 'AC Milan' },
    { player: 'Kayky', transferType: 'Transfer Out', club: 'Bahia' },
    { player: 'Kyle Walker', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Divin Mubama', transferType: 'Loan Out', club: 'Stoke' },
    { player: 'Sverre Nypan', transferType: 'Transfer In', club: 'Rosenborg' },
    { player: 'Maximo Perrone', transferType: 'Transfer Out', club: 'Como' },
    { player: 'James Trafford', transferType: 'Transfer In', club: 'Burnley' },
    { player: 'Jahmai Simpson-Pusey', transferType: 'Loan Out', club: 'Celtic' },
    { player: 'Vitor Reis', transferType: 'Loan Out', club: 'Girona' },
    { player: 'James McAtee', transferType: 'Transfer Out', club: 'Nottingham Forest' },
    { player: 'Sverre Nypan', transferType: 'Loan Out', club: 'Middlesborough' },
    { player: 'Jack Grealish', transferType: 'Loan Out', club: 'Everton' },
    { player: 'Claudio Echeverri', transferType: 'Loan Out', club: 'Bayer Leverkusen' },
    { player: 'Mahamadou Susoho', transferType: 'Loan Out', club: 'Livingston' },
    { player: 'Ederson', transferType: 'Transfer Out', club: 'Fenerbache' },
    { player: 'Manuel Akanji', transferType: 'Loan Out', club: 'Inter Milan' },
    { player: 'Gianluigi Donnarumma', transferType: 'Transfer In', club: 'Paris Saint-Germain' },
    { player: 'Ilkay Gundogan', transferType: 'Transfer Out', club: 'Galatasaray' }
  ],
  'Manchester United': [
    { player: 'Christian Eriksen', transferType: 'Released', club: '-' },
    { player: 'Jonny Evans', transferType: 'Released', club: 'Retired' },
    { player: 'Victor Lindelof', transferType: 'Released', club: '-' },
    { player: 'Matheus Cunha', transferType: 'Transfer In', club: 'Wolves' },
    { player: 'Diego Leon', transferType: 'Transfer In', club: 'Cerro Porteno' },
    { player: 'Sonny Aljofree', transferType: 'Loan Out', club: 'Notts County' },
    { player: 'Dan Gore', transferType: 'Loan Out', club: 'Rotherham' },
    { player: 'Joe Hugill', transferType: 'Loan Out', club: 'Barnet' },
    { player: 'Bryan Mbeumo', transferType: 'Transfer In', club: 'Brentford' },
    { player: 'Elyh Harrison', transferType: 'Loan Out', club: 'Shrewsbury Town' },
    { player: 'Marcus Rashford', transferType: 'Loan Out', club: 'Barcelona' },
    { player: 'Radek Vitek', transferType: 'Loan Out', club: 'Bristol City' },
    { player: 'Ethan Wheatley', transferType: 'Loan Out', club: 'Northampton Town' },
    { player: 'Jack Moorhouse', transferType: 'Loan Out', club: 'Leyton Orient' },
    { player: 'Benjamin Sesko', transferType: 'Transfer In', club: 'RB Leipzig' },
    { player: 'Toby Collyer', transferType: 'Loan Out', club: 'West Bromwich Albion' },
    { player: 'Louis Jackson', transferType: 'Loan Out', club: 'Solihull Moors' },
    { player: 'Alejandro Garnacho', transferType: 'Released', club: 'Chelsea' },
    { player: 'Ethan Williams', transferType: 'Loan Out', club: 'Falkirk' },
    { player: 'Ethan Ennis', transferType: 'Loan Out', club: 'Fleetwood Town' },
    { player: 'Rasmus Hojlund', transferType: 'Loan Out', club: 'Napoli' },
    { player: 'Antony', transferType: 'Transfer Out', club: 'Real Betis' },
    { player: 'Harry Amass', transferType: 'Loan Out', club: 'Sheffield Wednesday' },
    { player: 'Jadon Sancho', transferType: 'Loan Out', club: 'Aston Villa' },
    { player: 'Senne Lammens', transferType: 'Transfer In', club: 'Royal Antwerp' },
    { player: 'Andre Onana', transferType: 'Loan Out', club: 'Trabzonspor' }
  ],
  'Newcastle United': [
    { player: 'Antonio Cordero', transferType: 'Transfer In', club: 'Malaga' },
    { player: 'Anthony Elanga', transferType: 'Transfer In', club: 'Nottingham Forest' },
    { player: 'Jamal Lewis', transferType: 'Released', club: '-' },
    { player: 'Lloyd Kelly', transferType: 'Transfer Out', club: 'Juventus' },
    { player: 'Sean Longstaff', transferType: 'Transfer Out', club: 'Leeds' },
    { player: 'Seung-soo Park', transferType: 'Transfer In', club: 'Suwon Bluewings' },
    { player: 'Joe White', transferType: 'Loan Out', club: 'Leyton Orient' },
    { player: 'Josh Donaldson', transferType: 'Transfer Out', club: 'Hartlepool' },
    { player: 'Antonio Cordero', transferType: 'Loan Out', club: 'KVC Westerlo' },
    { player: 'Isaac Hayden', transferType: 'Released', club: 'QPR' },
    { player: 'Aaron Ramsdale', transferType: 'Loan In', club: 'Southampton' },
    { player: 'Martin Dubravka', transferType: 'Transfer Out', club: 'Burnley' },
    { player: 'Malick Thiaw', transferType: 'Transfer In', club: 'AC Milan' },
    { player: 'Jacob Ramsey', transferType: 'Transfer In', club: 'Aston Villa' },
    { player: 'Matt Targett', transferType: 'Loan Out', club: 'Middlesbrough' },
    { player: 'Garang Kuol', transferType: 'Transfer Out', club: 'Sparta Prague' },
    { player: 'Nick Woltemade', transferType: 'Transfer In', club: 'Stuttgart' },
    { player: 'Trevan Sanusi', transferType: 'Loan Out', club: 'FC Lorient' },
    { player: 'Alexander Isak', transferType: 'Transfer Out', club: 'Liverpool' },
    { player: 'Yoane Wissa', transferType: 'Transfer In', club: 'Brentford' },
    { player: 'Travis Hernes', transferType: 'Loan Out', club: 'Groningen' }
  ],
  'Nottingham Forest': [
    { player: 'Jack Perkins', transferType: 'Transfer Out', club: 'Northampton Town' },
    { player: 'Harry Toffolo', transferType: 'Released', club: 'Charlotte' },
    { player: 'Alex Moreno', transferType: 'End of loan', club: 'Aston Villa' },
    { player: 'Anthony Elanga', transferType: 'Transfer Out', club: 'Newcastle United' },
    { player: 'Andrew Omobamidele', transferType: 'Transfer Out', club: 'Strasbourg' },
    { player: 'Tyler Bindon', transferType: 'Loan Out', club: 'Sheffield United' },
    { player: 'Igor Jesus', transferType: 'Transfer In', club: 'Botafogo' },
    { player: 'Cherif Yaya', transferType: 'Transfer In', club: 'Rio Ave' },
    { player: 'Ramon Sosa', transferType: 'Transfer Out', club: 'Palmeiras' },
    { player: 'Ben Perry', transferType: 'Transfer Out', club: 'Colchester' },
    { player: 'Jair Cunha', transferType: 'Transfer In', club: 'Botafogo' },
    { player: 'Joe Gardner', transferType: 'Loan Out', club: 'Mansfield' },
    { player: 'Lewis O\'Brien', transferType: 'Transfer Out', club: 'Wrexham' },
    { player: 'Dan Ndoye', transferType: 'Transfer In', club: 'Bologna' },
    { player: 'Matt Turner', transferType: 'Transfer Out', club: 'Olympique Lyonnais' },
    { player: 'Josh Powell', transferType: 'Loan Out', club: 'Colchester United' },
    { player: 'Angus Gunn', transferType: 'Transfer In', club: 'Norwich' },
    { player: 'Dale Taylor', transferType: 'Transfer Out', club: 'Blackpool' },
    { player: 'Omari Hutchinson', transferType: 'Transfer In', club: 'Ipswich Town' },
    { player: 'James McAtee', transferType: 'Transfer In', club: 'Manchester City' },
    { player: 'Arnaud Kalimuendo', transferType: 'Transfer In', club: 'Rennes' },
    { player: 'Carlos Miguel', transferType: 'Transfer Out', club: 'Palmeiras' },
    { player: 'Marko Stamenic', transferType: 'Transfer Out', club: 'Swansea City' },
    { player: 'Douglas Luiz', transferType: 'Loan In', club: 'Juventus' },
    { player: 'David Carmo', transferType: 'Loan Out', club: 'Real Oviedo' },
    { player: 'George Murray-Jones', transferType: 'Loan Out', club: 'Chester' },
    { player: 'Nicolo Savona', transferType: 'Transfer In', club: 'Juventus' },
    { player: 'Emmanuel Dennis', transferType: 'Released', club: '-' },
    { player: 'John Victor', transferType: 'Transfer In', club: 'Botafogo' },
    { player: 'Eric da Silva Moreira', transferType: 'Loan Out', club: 'Rio Ave' },
    { player: 'Donnell McNeilly', transferType: 'Transfer In', club: 'Chelsea' },
    { player: 'Donnell McNeilly', transferType: 'Loan Out', club: 'Wycombe' },
    { player: 'Matthew Orr', transferType: 'Transfer In', club: 'Linfield' },
    { player: 'Josh Bowler', transferType: 'Released', club: '-' },
    { player: 'Cuiabano', transferType: 'Transfer In', club: 'Botafogo' },
    { player: 'Dilane Bakwa', transferType: 'Transfer In', club: 'Strasbourg' },
    { player: 'Oleksandr Zinchenko', transferType: 'Loan In', club: 'Arsenal' },
    { player: 'Omar Richards', transferType: 'Loan Out', club: 'Rio Ave' },
    { player: 'Chinaza Nwosu', transferType: 'Transfer In', club: 'West Ham United' },
    { player: 'Cuiabano', transferType: 'Loan Out', club: 'Botafogo' },
    { player: 'Jota Silva', transferType: 'Loan Out', club: 'Besiktas' }
  ],
  'Sunderland': [
    { player: 'Tommy Watson', transferType: 'Transfer Out', club: 'Brighton' },
    { player: 'Enzo Le Fee', transferType: 'Transfer In', club: 'Roma' },
    { player: 'Habib Diarra', transferType: 'Transfer In', club: 'Strasbourg' },
    { player: 'Jobe Bellingham', transferType: 'Transfer Out', club: 'Borussia Dortmund' },
    { player: 'Nathan Bishop', transferType: 'Transfer Out', club: 'Wimbledon' },
    { player: 'Noah Sadiki', transferType: 'Transfer In', club: 'Union Saint-Gilloise' },
    { player: 'Adil Aouchiche', transferType: 'Loan Out', club: 'Aberdeen' },
    { player: 'Reinildo Mandava', transferType: 'Transfer In', club: 'Atletico Madrid' },
    { player: 'Chemsdine Talbi', transferType: 'Transfer In', club: 'Club Brugge' },
    { player: 'Simon Adingra', transferType: 'Transfer In', club: 'Brighton' },
    { player: 'Matty Young', transferType: 'Loan Out', club: 'Salford City' },
    { player: 'Granit Xhaka', transferType: 'Transfer In', club: 'Bayer Leverkusen' },
    { player: 'Robin Roefs', transferType: 'Transfer In', club: 'NEC Nijmegen' },
    { player: 'Marc Guiu', transferType: 'Loan In', club: 'Chelsea' },
    { player: 'Arthur Masuaku', transferType: 'Transfer In', club: 'Besiktas' },
    { player: 'Omar Alderete', transferType: 'Transfer In', club: 'Getafe' },
    { player: 'Tom Lavery', transferType: 'Loan Out', club: 'Cliftonville' },
    { player: 'Pierre Ekwah', transferType: 'Transfer Out', club: 'AS Saint-Etienne' },
    { player: 'Nordi Mukiele', transferType: 'Transfer In', club: 'Paris Saint-Germain' },
    { player: 'Alan Browne', transferType: 'Loan Out', club: 'Middlesbrough' },
    { player: 'Jenson Seelt', transferType: 'Loan Out', club: 'Wolfsburg' },
    { player: 'Lutsharel Geertruida', transferType: 'Loan In', club: 'RB Leipzig' },
    { player: 'Marc Guiu', transferType: 'End of loan', club: 'Chelsea' },
    { player: 'Niall Huggins', transferType: 'Loan Out', club: 'Wycombe Wanderers' },
    { player: 'Patrick Roberts', transferType: 'Loan Out', club: 'Birmingham City' },
    { player: 'Oliver Bainbridge', transferType: 'Loan Out', club: 'South Shields' },
    { player: 'Brian Brobbey', transferType: 'Transfer In', club: 'Ajax' },
    { player: 'Bertrand Traore', transferType: 'Transfer In', club: 'Ajax' },
    { player: 'Nazariy Rusyn', transferType: 'Loan Out', club: 'Arka' },
    { player: 'Milan Aleksic', transferType: 'Loan Out', club: 'Cracovia' },
    { player: 'Nectar Triantis', transferType: 'Transfer Out', club: 'Minnesota United' },
    { player: 'Luis Hemir', transferType: 'Loan Out', club: 'Moreirense FC' }
  ],
  'Tottenham Hotspur': [
    { player: 'Luka Vuskovic', transferType: 'Transfer In', club: 'Hajduk Split' },
    { player: 'Fraser Forster', transferType: 'Released', club: '-' },
    { player: 'Sergio Reguilon', transferType: 'Released', club: '-' },
    { player: 'Alfie Whiteman', transferType: 'Released', club: '-' },
    { player: 'Timo Werner', transferType: 'End of loan', club: 'Leipzig' },
    { player: 'Pierre-Emile Hojbjerg', transferType: 'Transfer Out', club: 'Marseille' },
    { player: 'Kevin Danso', transferType: 'Transfer In', club: 'Lens' },
    { player: 'Mathys Tel', transferType: 'Transfer In', club: 'Bayern Munich' },
    { player: 'Damola Ajayi', transferType: 'Loan Out', club: 'Doncaster Rovers' },
    { player: 'Max McFadden', transferType: 'Transfer In', club: 'Leeds' },
    { player: 'Kota Takai', transferType: 'Transfer In', club: 'Kawasaki Frontale' },
    { player: 'Alejo Veliz', transferType: 'Loan Out', club: 'Rosario Central' },
    { player: 'Mohammed Kudus', transferType: 'Transfer In', club: 'West Ham' },
    { player: 'Josh Keeley', transferType: 'Transfer Out', club: 'Luton Town' },
    { player: 'Alfie Dorrington', transferType: 'Loan Out', club: 'Aberdeen' },
    { player: 'Ashley Phillips', transferType: 'Loan Out', club: 'Stoke City' },
    { player: 'Mikey Moore', transferType: 'Loan Out', club: 'Rangers' },
    { player: 'Joao Palhinha', transferType: 'Loan In', club: 'Bayern Munich' },
    { player: 'Tyrese Hall', transferType: 'Loan Out', club: 'Notts County' },
    { player: 'Will Lankshear', transferType: 'Loan Out', club: 'Oxford United' },
    { player: 'Jamie Donley', transferType: 'Loan Out', club: 'Stoke' },
    { player: 'George Abbott', transferType: 'Loan Out', club: 'Wycombe Wanderers' },
    { player: 'Son Heung-min', transferType: 'Transfer Out', club: 'LAFC' },
    { player: 'Yang Min-Hyeok', transferType: 'Loan Out', club: 'Portsmouth' },
    { player: 'Alfie Devine', transferType: 'Loan Out', club: 'Preston' },
    { player: 'Luka Vuskovic', transferType: 'Loan Out', club: 'Hamburg' },
    { player: 'Xavi Simons', transferType: 'Transfer In', club: 'Leipzig' },
    { player: 'Randal Kolo Muani', transferType: 'Loan In', club: 'Paris Saint-Germain' },
    { player: 'Bryan Gil', transferType: 'Transfer Out', club: 'Girona' },
    { player: 'Manor Solomon', transferType: 'Loan Out', club: 'Villarreal CF' }
  ],
  'West Ham United': [
    { player: 'Aaron Cresswell', transferType: 'Released', club: 'Stoke' },
    { player: 'Lukasz Fabianski', transferType: 'Released', club: '-' },
    { player: 'Vladimir Coufal', transferType: 'Released', club: 'Hoffenheim' },
    { player: 'Danny Ings', transferType: 'Released', club: '-' },
    { player: 'Kamarai Swyer', transferType: 'Released', club: 'Northampton Town' },
    { player: 'Jean-Clair Todibo', transferType: 'Transfer In', club: 'OGC Nice' },
    { player: 'Carlos Soler', transferType: 'End of loan', club: 'PSG' },
    { player: 'Evan Ferguson', transferType: 'End of loan', club: 'Brighton' },
    { player: 'Kurt Zouma', transferType: 'Released', club: 'Al-Orobah' },
    { player: 'Brad Dolaghan', transferType: 'Released', club: 'Worthing' },
    { player: 'Daniel Cummings', transferType: 'Transfer In', club: 'Celtic' },
    { player: 'Mohammed Kudus', transferType: 'Transfer Out', club: 'Spurs' },
    { player: 'El Hadji Malick Diouf', transferType: 'Transfer In', club: 'Slavia Prague' },
    { player: 'Kyle Walker-Peters', transferType: 'Transfer In', club: 'Southampton' },
    { player: 'Gideon Kodua', transferType: 'Loan Out', club: 'Luton Town' },
    { player: 'Michael Forbes', transferType: 'Loan Out', club: 'Northampton' },
    { player: 'Sean Moore', transferType: 'Transfer Out', club: 'Shelbourne' },
    { player: 'Patrick Kelly', transferType: 'Transfer Out', club: 'Barnsley' },
    { player: 'Callum Wilson', transferType: 'Transfer In', club: 'Newcastle' },
    { player: 'Kaelan Casey', transferType: 'Loan Out', club: 'Swansea' },
    { player: 'Michail Antonio', transferType: 'Released', club: '-' },
    { player: 'Mads Hermansen', transferType: 'Transfer In', club: 'Leicester' },
    { player: 'Luizao', transferType: 'Released', club: '-' },
    { player: 'Edson Alvarez', transferType: 'Loan Out', club: 'Fenerbahce' },
    { player: 'Mateus Fernandes', transferType: 'Transfer In', club: 'Southampton' },
    { player: 'Soungoutou Magassa', transferType: 'Transfer In', club: 'AS Monaco' },
    { player: 'Junior Robinson', transferType: 'Loan Out', club: 'Livingston' },
    { player: 'Emerson Palmieri', transferType: 'Transfer Out', club: 'Marseille' },
    { player: 'Lewis Orford', transferType: 'Loan Out', club: 'Stevenage' },
    { player: 'Finlay Herrick', transferType: 'Loan Out', club: 'Boreham Wood' },
    { player: 'Igor Julio', transferType: 'Loan In', club: 'Brighton' },
    { player: 'Maxwel Cornet', transferType: 'Loan Out', club: 'Genoa' },
    { player: 'Nayef Aguerd', transferType: 'Transfer Out', club: 'Marseille' },
    { player: 'Wes Foderingham', transferType: 'Transfer Out', club: 'Aris Limassol' },
    { player: 'Lukasz Fabianski', transferType: 'Transfer In', club: '-' }
  ],
  'Wolverhampton Wanderers': [
    { player: 'Pablo Sarabia', transferType: 'Released', club: 'Al-Arabi' },
    { player: 'Matheus Cunha', transferType: 'Transfer Out', club: 'Man Utd' },
    { player: 'Craig Dawson', transferType: 'Released', club: '-' },
    { player: 'Carlos Forbs', transferType: 'End of loan', club: 'Ajax' },
    { player: 'Matty Whittingham', transferType: 'Released', club: '-' },
    { player: 'Rayan Ait-Nouri', transferType: 'Transfer Out', club: 'Man City' },
    { player: 'Hugo Bueno', transferType: 'End of loan', club: 'Feyenoord' },
    { player: 'Fer Lopez', transferType: 'Transfer In', club: 'Celta Vigo' },
    { player: 'Chem Campbell', transferType: 'Transfer Out', club: 'Stevenage' },
    { player: 'Jorgen Strand Larsen', transferType: 'Transfer In', club: 'Celta Vigo' },
    { player: 'Tommy Doyle', transferType: 'Loan Out', club: 'Birmingham City' },
    { player: 'Nasser Djiga', transferType: 'Loan Out', club: 'Rangers' },
    { player: 'Chiquinho', transferType: 'Transfer Out', club: 'Alverca' },
    { player: 'Nigel Lonwijk', transferType: 'Loan Out', club: 'Luton' },
    { player: 'Joe Hodge', transferType: 'Transfer Out', club: 'CD Tondela' },
    { player: 'Bastien Meupiyou', transferType: 'Transfer Out', club: 'Alverca' },
    { player: 'Boubacar Traore', transferType: 'Loan Out', club: 'Metz' },
    { player: 'Jhon Arias', transferType: 'Transfer In', club: 'Fluminense' },
    { player: 'Nelson Semedo', transferType: 'Released', club: 'Fenerbahce' },
    { player: 'David Moller Wolfe', transferType: 'Transfer In', club: 'AZ Alkmaar' },
    { player: 'Goncalo Guedes', transferType: 'Transfer Out', club: 'Real Sociedad' },
    { player: 'Tom King', transferType: 'Transfer Out', club: 'Everton' },
    { player: 'Jackson Tchatchoua', transferType: 'Transfer In', club: 'Verona' },
    { player: 'Ladislav Krejci', transferType: 'Loan In', club: 'Girona' },
    { player: 'Fabio Silva', transferType: 'Transfer Out', club: 'Borussia Dortmund' },
    { player: 'Tolu Arokodare', transferType: 'Transfer In', club: 'Genk' },
    { player: 'Pedro Lima', transferType: 'Loan Out', club: 'Porto' },
    { player: 'Sasa Kalajdzic', transferType: 'Loan Out', club: 'LASK' }
  ]
};

export class TransferDataParserService {
  private static instance: TransferDataParserService;

  static getInstance(): TransferDataParserService {
    if (!TransferDataParserService.instance) {
      TransferDataParserService.instance = new TransferDataParserService();
    }
    return TransferDataParserService.instance;
  }

  private mapTransferEntryToTransfer(entry: TransferEntry, teamName: string): Transfer {
    const now = new Date().toISOString();
    let status: 'confirmed' | 'rumored' | 'pending' = 'confirmed';
    let fromClub = '';
    let toClub = '';
    let fee = 'Undisclosed';

    // Determine transfer direction and status
    switch (entry.transferType) {
      case 'Transfer In':
        fromClub = entry.club;
        toClub = teamName;
        fee = 'Undisclosed';
        break;
      case 'Transfer Out':
        fromClub = teamName;
        toClub = entry.club;
        fee = 'Undisclosed';
        break;
      case 'Loan In':
        fromClub = entry.club;
        toClub = teamName;
        fee = 'Loan';
        break;
      case 'Loan Out':
        fromClub = teamName;
        toClub = entry.club;
        fee = 'Loan';
        break;
      case 'Released':
        fromClub = teamName;
        toClub = entry.club === '-' ? 'Free Agent' : entry.club;
        fee = 'Free';
        break;
      case 'End of loan':
        fromClub = teamName;
        toClub = entry.club;
        fee = 'End of Loan';
        break;
    }

    return {
      id: `transfer-${teamName.toLowerCase().replace(/\s+/g, '-')}-${entry.player.toLowerCase().replace(/\s+/g, '-')}-2025`,
      playerName: entry.player,
      fromClub,
      toClub,
      fee,
      date: now,
      source: 'Manual Data Entry',
      status
    };
  }

  getTeamTransfers(teamName: string): Transfer[] {
    const entries = TEAMS_TRANSFER_DATA[teamName] || [];
    return entries.map(entry => this.mapTransferEntryToTransfer(entry, teamName));
  }

  getAllTransfers(): Transfer[] {
    const allTransfers: Transfer[] = [];
    
    for (const [teamName, entries] of Object.entries(TEAMS_TRANSFER_DATA)) {
      const teamTransfers = entries.map(entry => this.mapTransferEntryToTransfer(entry, teamName));
      allTransfers.push(...teamTransfers);
    }

    // Sort by date (newest first)
    return allTransfers.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }

  getAvailableTeams(): string[] {
    return Object.keys(TEAMS_TRANSFER_DATA);
  }
}

export const transferDataParser = TransferDataParserService.getInstance();