import axios from 'axios';
import * as cheerio from 'cheerio';
import fs from 'fs';

const SKY_URL = 'https://www.skysports.com/football/transfers';
const BBC_URL = 'https://www.bbc.com/sport/football/';
const TRANSFERMARKT_URL = 'https://www.transfermarkt.com/premier-league/transfers/wettbewerb/GB1';

async function scrapeSkySports() {
  const { data } = await axios.get(SKY_URL);
  const $ = cheerio.load(data);
  const transfers: any[] = [];
  $('.news-list__item').each((_, el) => {
    const headline = $(el).find('.news-list__headline').text().trim();
    const summary = $(el).find('.news-list__snippet').text().trim();
    if (headline && summary) {
      transfers.push({
        headline,
        summary,
        source: 'Sky Sports',
        date: new Date().toISOString(),
      });
    }
  });
  return transfers;
}

async function scrapeBBC() {
  const { data } = await axios.get(BBC_URL);
  const $ = cheerio.load(data);
  const transfers: any[] = [];
  // BBC main headlines (may need adjustment for transfer-specific page)
  $('[data-testid="top-stories-primary-item"]').each((_, el) => {
    const headline = $(el).find('h3').text().trim();
    const summary = $(el).find('p').text().trim();
    if (headline && (headline.toLowerCase().includes('transfer') || summary.toLowerCase().includes('transfer'))) {
      transfers.push({
        headline,
        summary,
        source: 'BBC',
        date: new Date().toISOString(),
      });
    }
  });
  return transfers;
}

async function scrapeTransfermarkt() {
  const { data } = await axios.get(TRANSFERMARKT_URL);
  const $ = cheerio.load(data);
  const transfers: any[] = [];
  // Transfermarkt table rows (summer window)
  $('table.items > tbody > tr').each((_, el) => {
    const player = $(el).find('td:nth-child(2) .spielprofil_tooltip').text().trim();
    const fromClub = $(el).find('td:nth-child(5) .vereinprofil_tooltip').text().trim();
    const toClub = $(el).find('td:nth-child(9) .vereinprofil_tooltip').text().trim();
    const fee = $(el).find('td.rechts').last().text().trim();
    if (player && (fromClub || toClub)) {
      transfers.push({
        player,
        fromClub,
        toClub,
        fee,
        source: 'Transfermarkt',
        date: new Date().toISOString(),
      });
    }
  });
  return transfers;
}

function dedupeTransfers(arr: any[]): any[] {
  const seen = new Set();
  return arr.filter(item => {
    const key = item.headline || (item.player + item.fromClub + item.toClub);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

async function main() {
  try {
    const [skyTransfers, bbcTransfers, tmTransfers] = await Promise.all([
      scrapeSkySports(),
      scrapeBBC(),
      scrapeTransfermarkt()
    ]);
    const allTransfers = dedupeTransfers([
      ...skyTransfers,
      ...bbcTransfers,
      ...tmTransfers
    ]);
    fs.writeFileSync(
      './src/data/transfers/rumors.ts',
      `// Auto-generated by scrapeTransfers.ts\nexport const latestRumors = ${JSON.stringify(allTransfers, null, 2)};\n`
    );
    console.log('Rumors updated:', allTransfers.length);
  } catch (err) {
    console.error('Scrape failed:', err);
  }
}

main();
