/**
 * FBref URL config for pull/scrape: comp URL, club squad URLs, and player URLs per club.
 * Data is loaded from public/fbref-urls.json (generated by scripts/scrapeFbrefUrls.mjs).
 *
 * @see scripts/scrapeFbrefUrls.mjs
 */

export const FBREF_COMP_URL = 'https://fbref.com/en/comps/9/Premier-League-Stats';

export interface FbrefPlayerUrl {
  name: string;
  url: string;
}

export interface FbrefClubUrls {
  name: string;
  slug: string;
  squadUrl: string;
  players: FbrefPlayerUrl[];
  error?: string;
}

export interface FbrefUrlsConfig {
  compUrl: string;
  scrapedAt?: string;
  clubs: FbrefClubUrls[];
}

let cachedConfig: FbrefUrlsConfig | null = null;

/** Clear in-memory cache so next loadFbrefUrls() refetches. */
export function clearFbrefUrlsCache(): void {
  cachedConfig = null;
}

/**
 * Load FBref URLs from public/fbref-urls.json. Cached in memory.
 * Returns null if file missing or invalid.
 */
export async function loadFbrefUrls(): Promise<FbrefUrlsConfig | null> {
  if (cachedConfig) return cachedConfig;
  try {
    const res = await fetch('/fbref-urls.json', { cache: 'no-cache' });
    if (!res.ok) return null;
    const data = (await res.json()) as FbrefUrlsConfig;
    if (!data?.clubs || !Array.isArray(data.clubs)) return null;
    cachedConfig = {
      compUrl: data.compUrl || FBREF_COMP_URL,
      scrapedAt: data.scrapedAt,
      clubs: data.clubs,
    };
    return cachedConfig;
  } catch {
    return null;
  }
}

/**
 * Get club URLs by slug.
 */
export function getFbrefClubBySlug(config: FbrefUrlsConfig | null, slug: string): FbrefClubUrls | undefined {
  if (!config) return undefined;
  return config.clubs.find((c) => c.slug === slug || c.name.toLowerCase().replace(/\s+/g, '-') === slug);
}
